genx/clothing/urls.py
from django.urls import path, include
from clothing import views

app_name= 'clothing'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:item_id>/', views.detail, name='detail'),
    path('mens/', views.mens, name='mens'),
    path('womens/', views.womens, name='womens'),
    path('kids/', views.kids, name='kids'),
    path('orders/<int:id>/<int:pdcd>/<str:user>/', views.Orders, name='orders'),
    path('add_to_cart/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_view, name='cart_view'),
    path('remove_from_cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('myorders/', views.Orders, name='myorders'),
    path('orders/<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),
]

genx/genx/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as users_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clothing.urls')),
    path('users/', include('users.urls')),
    path('register/', users_views.register, name='register'),
    path('login/', users_views.login_view, name='login'),
    path('logout/', users_views.logout_view, name='logout'),
    path('profile/', users_views.profilepage, name='profile'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]

urlpatterns += [] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

genx/users/urls.py
from users import views
from django.urls import path

app_name = 'users'
urlpatterns = [
    
    # paypal checkout button
    path('payment/<grand_total>/', views.payment_view, name='payment'),

    # paypal on approve
    path('oa/', views.OnApprove, name='oa'),

    # paypal payment success
    path('ps/', views.PaymentSuccess, name='ps'),
]

genx/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100, default='Mumbai')

    def __str__(self):
        return self.user.username

genx/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import  MaxValueValidator, MinValueValidator, RegexValidator

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(
        validators=[
            RegexValidator(
                regex='^[a-zA-Z]+$',
                message='First Name must contain only alphabets.',
            ),
        ],
    )
    last_name = forms.CharField(
        validators=[
            RegexValidator(
                regex='^[a-zA-Z]+$',
                message='Last Name must contain only alphabets.',
            ),
        ],
    )
    mob_num = forms.IntegerField(
        label='Mobile Number',
        validators=[
            RegexValidator(
                regex='^[0-9]{10}$',
                message='Mobile Number must be a 10-digit numeric value.',
            ),
            MaxValueValidator(9999999999, message='Mobile number must be at most 10 digits.'),
            MinValueValidator(1000000000, message='Enter a valid mobile number with only numeric characters.'),
        ],
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'mob_num', 'password1', 'password2']

genx/users/views.py
from django.shortcuts import render, redirect
from users.forms import RegisterForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from clothing.models import CartItem
from clothing.views import create_orders_from_cart
from django.http import JsonResponse
import json

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')

            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username already exists. Please choose a different username.')
            else:
                messages.success(
                    request,
                    'Welcome {}, your account has been successfully created. Now you may log in'.format(username)
                )
                form.save()
                return redirect('login')

    else:
        form = RegisterForm()

    context = {'form': form}
    return render(request, 'users/register.html', context)


def login_view(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is None:
            messages.success(
                request,
                'Invalid Login, try again'
            )
            return redirect('login')

        elif user.is_superuser:
            login(request, user)
            messages.success(
                request,
                'Welcome Superuser {}, you have been successfully logged in'.format(
                    request.user.username)
            )
            return redirect('clothing:index')

        elif user is not None:
            login(request, user)
            messages.success(
                request,
                'Welcome {}, you have been successfully logged in'.format(
                    request.user.username)
            )
            return redirect('clothing:index')

    return render(request, 'users/login.html')


def logout_view(request):
    messages.success(
        request,
        '{}, you have successfully logged out'.format(request.user.username)
    )
    logout(request)
    return redirect('clothing:index')


@login_required
def profilepage(request):
    return render(request, 'users/profile.html')


def payment_view(request, grand_total):
    context = {
        'grand_total': grand_total,
    }

    return render(request, 'users/payment.html', context)

def OnApprove(request):

    if request.method == 'POST':
        body = json.loads(request.body)
        print(body)

        context = {

        }

        return JsonResponse(context)


def PaymentSuccess(request):
    cart_items = CartItem.objects.filter(user=request.user)
    
    orders_created = create_orders_from_cart(request, cart_items)

    cart_items.delete()

    return render(request, 'users/pymtsuccess.html', {'orders_created': orders_created})

genx/users/templates/users/login.html
{% extends 'clothing/base.html' %} {% block body %}


<br><br><br><br><br><br>
<center>
<div class="card text" style="width:40%">
    <div class="card-header" style="background-color: #98f0ff; color: #000000; font-weight: bold;">Login</div>
        <div class="card-body">
            <p class="card-text">
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label
                            for="user"
                            class="form-label"
                            >Username</label
                        >
                        <input
                            type="text"
                            class="form-control"
                            id="user"
                            name="username" />
                    </div>
                    <div class="mb-3">
                        <label
                            for="pass"
                            class="form-label"
                            >Password</label
                        >
                        <input
                            type="password"
                            class="form-control"
                            id="pass"
                            name="password" />
                    </div>
                    <br>
                    <button
                        type="submit"
                        class="btn btn-primary"
                        style="width: 50%;">
                        Submit
                    </button>
                </form>
                <br>
                <p><a href="{% url 'password_reset' %}">Forgot your Password?</a></p>
                
                <div>Don't have an account <a href="{% url 'register' %}">Sign Up</a></div>
            </p>
        </div>
</div>
</center>
{% endblock %}

genx/users/templates/users/payment.html
{% extends 'clothing/base.html' %}

{% block body %}

<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var totamt = "{{ grand_total }}";
    var url = "{% url 'users:oa' %}";
    var csrftoken = getCookie('csrftoken');
    var redirect_url = "{% url 'users:ps' %}";

    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        style: {
            color:  'blue',
            shape:  'pill',
            label:  'pay',
            height: 40,
        },

        // Call your server to set up the transaction
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: totamt
                    }
                }]
            });
        },

        // Call your server to finalize the transaction
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                console.log(details);
                SendData();
                //alert('Transaction completed by ' + details.payer.name.given_name + '!');
                function SendData() {
                    // url : gives the path to where our data goes
                    fetch(url, {
                        method: "POST",
                        headers: {
                            "Content-type": "application/json",
                            "X-CSRFToken": csrftoken,
                        },
                        body: JSON.stringify({
                            orderID: 10,
                            transID: details.id,
                            payment_method: 'Test',
                            status: details.status,
                        }),
                    })
                    .then((response) => response.json())
                    //.then(data => console.log(data));
                    .then((data) => {
                        window.location.href = redirect_url;
                    });
                }
            });
        }
    }).render('#paypal-button-container');
</script>
<br><br><br>
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <div class="box-element" id="form-wrapper">
                {% comment %} <form id="form">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="inputFirst" class="form-label">First Name</label>
                            <input type="text" class="form-control" placeholder="First name" aria-label="First name" required>
                        </div>
                        <div class="col-md-6">
                            <label for="inputLast" class="form-label">Last Name</label>
                            <input type="text" class="form-control" placeholder="Last name" aria-label="Last name" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="inputEmail4" class="form-label">Email</label>
                            <input type="email" class="form-control" id="inputEmail4" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <label for="inputAddress" class="form-label">Address</label>
                            <input type="text" class="form-control" id="inputAddress" placeholder="Flat number and Building name" required>
                        </div>
                        <div class="col-12">
                            <label for="inputAddress2" class="form-label">Address 2</label>
                            <input type="text" class="form-control" id="inputAddress2" placeholder="Area name and Landmark" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="inputCity" class="form-label">City</label>
                            <input type="text" class="form-control" id="inputCity" required>
                        </div>
                        <div class="col-md-4">
                            <label for="inputState" class="form-label">State</label>
                            <input type="text" class="form-control" id="inputState" required>
                        </div>
                        <div class="col-md-4">
                            <label for="inputZip" class="form-label">Pin Code</label>
                            <input type="number" class="form-control" id="inputZip" min="100000" max="999999" required>
                        </div>
                    </div>
                    <br>
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-success btn-block">Save</button>
                    </div>
                </form> {% endcomment %}
            </div>
        </div>

        <div class="col-lg-6">
            <div class="box-element">
                <h3>
                    Pay ₹{{ grand_total }}
                </h3>
                <div id="paypal-button-container">
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

genx/users/templates/users/profile.html
{% extends 'clothing/base.html' %}
{% block body %}

<br><br><br>

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Profile
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="offset-md-1">
                            <img style="margin-bottom: 15px;" height="100px" width="100px" src="{{ user.profile.image.url }}">
                        </div>
                        <div style="margin-top: 20px;" class="offset-md-2">
                            <span>{{ user.first_name }}</span>
                            <span>{{ user.last_name }}</span><br>
                            <span>{{ user.email }}</span>
                            <p>{{ user.profile.location }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<br><br><br>

{% endblock %}

genx/users/templates/users/pymtsuccess.html
{% extends 'clothing/base.html' %}

{% block body %}

<html>
  <head>

  </head>
    <style>
      body {
        text-align: center;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>
    <body>
      <div class="card mt-5">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>Success</h1> 
        <p>We have received your order</p>
        <br>
        <a href="{% url 'clothing:index' %}" class="btn btn-dark">
        Back to Home
        </a>
      </div>

    </body>
</html>

{% endblock %}

genx/users/templates/users/register.html
{% extends 'clothing/base.html' %}

{% block body %}

<br><br><br>
<div class="container mt-5">
	<div class="card mx-auto" style="max-width: 40%">
		<div class="card-header text-center" style="background-color: #98f0ff; color: #000000; font-weight: bold;">
			Register
		</div>
		<div class="card-body">
			<form method="POST">
				{% csrf_token %}
				<div class="form-group row">
					<label for="username" class="col-sm-5 col-form-label text-right">Username:</label>
					<div class="col-sm-7">
						{{ form.username }}
						{% for error in form.username.errors %}
						<p class="text-danger">{{ error }}</p>
						{% endfor %}
					</div>
				</div>
				<div class="form-group row">
					<label for="email" class="col-sm-5 col-form-label text-right">Email:</label>
					<div class="col-sm-7">
						{{ form.email }}
						{% for error in form.email.errors %}
						<p class="text-danger">{{ error }}</p>
						{% endfor %}
					</div>
				</div>
				<div class="form-group row">
					<label for="first_name" class="col-sm-5 col-form-label text-right">First Name:</label>
					<div class="col-sm-7">
						{{ form.first_name }}
						{% for error in form.first_name.errors %}
						<p class="text-danger">{{ error }}</p>
						{% endfor %}
					</div>
				</div>
				<div class="form-group row">
					<label for="last_name" class="col-sm-5 col-form-label text-right">Last Name:</label>
					<div class="col-sm-7">
						{{ form.last_name }}
						{% for error in form.last_name.errors %}
						<p class="text-danger">{{ error }}</p>
						{% endfor %}
					</div>
				</div>
				<div class="form-group row">
					<label for="mob_num" class="col-sm-5 col-form-label text-right">Mobile Number:</label>
					<div class="col-sm-7">
						{{ form.mob_num }}
						{% for error in form.mob_num.errors %}
						<p class="text-danger">{{ error }}</p>
						{% endfor %}
					</div>
				</div>
				<div class="form-group row">
					<label for="password1" class="col-sm-5 col-form-label text-right">Password:</label>
					<div class="col-sm-7">
						{{ form.password1 }}
						{% for error in form.password1.errors %}
						<p class="text-danger">{{ error }}</p>
						{% endfor %}
					</div>
				</div>
				<div class="form-group row">
					<label for="password2" class="col-sm-5 col-form-label text-right">Confirm Password:</label>
					<div class="col-sm-7">
						{{ form.password2 }}
						{% for error in form.password2.errors %}
						<p class="text-danger">{{ error }}</p>
						{% endfor %}
					</div>
				</div>
				<br>
				<div class="form-group row">
					<div class=" text-center">
						<button class="btn btn-primary" type="submit" style="width: 70%;">Sign Up</button>
					</div>
				</div>
			</form>
			<br>
			<div class="text-center">
				Already have an account? <a href="{% url 'login' %}">Login</a>
			</div>
		</div>
	</div>
</div>

{% endblock %}