genx/clothing/urls.py
from django.urls import path, include
from clothing import views

app_name= 'clothing'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:item_id>/', views.detail, name='detail'),
    path('mens/', views.mens, name='mens'),
    path('womens/', views.womens, name='womens'),
    path('kids/', views.kids, name='kids'),
    path('orders/<int:id>/<int:pdcd>/<str:user>/', views.Orders, name='orders'),
    path('add_to_cart/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_view, name='cart_view'),
    path('remove_from_cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('myorders/', views.Orders, name='myorders'),
    path('orders/<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),
]

genx/genx/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as users_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clothing.urls')),
    path('users/', include('users.urls')),
    path('register/', users_views.register, name='register'),
    path('login/', users_views.login_view, name='login'),
    path('logout/', users_views.logout_view, name='logout'),
    path('profile/', users_views.profilepage, name='profile'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]

urlpatterns += [] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

genx/users/urls.py
from users import views
from django.urls import path

app_name = 'users'
urlpatterns = [
    
    # paypal checkout button
    path('payment/<grand_total>/', views.payment_view, name='payment'),

    # paypal on approve
    path('oa/', views.OnApprove, name='oa'),

    # paypal payment success
    path('ps/', views.PaymentSuccess, name='ps'),
]

genx/clothing/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    CATEGORY_CHOICES = (
        ('m', 'Mens'),
        ('f', 'Womens'),
        ('k', 'Kids'),
    )

    item_name = models.CharField(max_length=50)
    item_desc = models.CharField(max_length=300)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://media.istockphoto.com/id/1273109788/vector/coming-soon-isolated-vector-icon-paper-style-promotion-sign-start-a-new-business-design.jpg?s=612x612&w=0&k=20&c=0APH6QCc371SuCEYLspgp6oh-tE5-rvbK0dzLMRmJGA=")
    category = models.CharField(max_length=1, choices=CATEGORY_CHOICES, default="m")

    def __str__(self):
        return self.item_name

class CusOrders(models.Model):
    size = (
        ('XS', 'Extra Small'),
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
        ('XL', 'Extra Large'),
    )
    order_status_choices = (
        ('Order Confirmed', 'Order Confirmed'),
        ('Shipped', 'Shipped'),
        ('Out for Delivery', 'Out for Delivery'),
        ('Delivered', 'Delivered'),

    )
    order_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    size = models.CharField(max_length=2, choices=size, default='M')
    order_status = models.CharField(max_length=20, choices=order_status_choices, default='Order Confirmed')

    def __str__(self):
        return f"[Order ID: {self.order_id}] {self.quantity} x {self.item.item_name} (Size: {self.size}) {self.user.username}'s order (Status: {self.order_status})"

class CartItem(models.Model):
    size = (
        ('XS', 'Extra Small'),
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
        ('XL', 'Extra Large'),
    )
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    size = models.CharField(max_length=2, choices=size, default='M')

    def __str__(self):
        return f"{self.quantity} x {self.item.item_name} (Size: {self.size}) in {self.user.username}'s cart"

genx/clothing/views.py
from django.shortcuts import render
from clothing.models import Item
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from clothing.models import Item, CartItem, CusOrders
from django.contrib import messages
from django.core.mail import send_mail

# Create your views here.

def index(request):
    itemlist = Item.objects.all()
    
    # for search functionality
    item_name = request.POST.get('item_name')
    if item_name != '' and item_name is not None:
        itemlist = Item.objects.filter(item_name__icontains=item_name)
    else:
        itemlist = Item.objects.all()
        
    context = {
        'itemlist':itemlist
    }
    
    if not itemlist:
        messages.info(request, 'No search results found.')
        
    return render(request, 'clothing/index.html', context)

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    
    context = {
        'item':item,
    }
    
    return render(request, 'clothing/detail.html', context)


def mens(request):
    itemlist = Item.objects.filter(category='m')

    context = {
        'itemlist': itemlist
    }

    return render(request, 'clothing/mens.html', context)


def womens(request):
    itemlist = Item.objects.filter(category='f')

    context = {
        'itemlist': itemlist
    }

    return render(request, 'clothing/womens.html', context)


def kids(request):
    itemlist = Item.objects.filter(category='k')
    
    context = {
        'itemlist': itemlist
    }

    return render(request, 'clothing/kids.html', context)


@login_required
def Orders(request):
    user = request.user

    if request.method == 'POST':
        Obj_CusOrds = CusOrders(
            user=user,
            quantity=request.POST.get('qty'),
            size=request.POST.get('size')
        )
        Obj_CusOrds.save()

    else:
        previous_orders = CusOrders.objects.filter(user=user)
        for order in previous_orders:
            order.total_amount = order.item.item_price * order.quantity
        grand_total = sum(order.item.item_price * order.quantity for order in previous_orders)
        context = {'previous_orders': previous_orders, 'grand_total': grand_total,}
        return render(request, 'clothing/myorders.html', context)

@login_required
def add_to_cart(request, item_id):
    item = get_object_or_404(Item, pk=item_id)

    if request.method == 'POST':
        selected_size = request.POST.get('size')
        quantity = int(request.POST.get('qty', 1))

        if quantity < 1:
            quantity = 1
        elif quantity > 10:
            quantity = 10
        if request.user.is_authenticated:
            cart_item, created = CartItem.objects.get_or_create(
                user=request.user, item=item, size=selected_size
            )

            if not created:
                cart_item.quantity += quantity
            else:
                cart_item.quantity = quantity

            cart_item.save()

        return redirect('clothing:cart_view')

    return redirect('clothing:cart_view')


def cart_view(request):
    cart_items = CartItem.objects.filter(user=request.user).select_related('item')

    grand_total = sum(cart_item.item.item_price * cart_item.quantity for cart_item in cart_items)

    for cart_item in cart_items:
        cart_item.total_price = cart_item.item.item_price * cart_item.quantity

    return render(request, 'clothing/cart.html', {'cart_items': cart_items, 'grand_total': grand_total})


def remove_from_cart(request, cart_item_id):
    cart_item = get_object_or_404(CartItem, pk=cart_item_id)

    if request.user == cart_item.user:
        cart_item.delete()

    return redirect('clothing:cart_view')


def create_order(cart_item, user, request):
    try:
        order = CusOrders.objects.create(
            user=user,
            item=cart_item.item,
            quantity=cart_item.quantity,
            size=cart_item.size
        )
        send_mail(
            "Your Order has been successfully placed",
            f"Dear {order.user},\n\n"
            f"Your order #{order.order_id} has been successfully placed!\n"                    
            f"Here are the details:\n"
            f"- Item Name: {order.item.item_name}\n"
            f"- Size: {order.size}\n"                f"- Quantity: {order.quantity}\n"
            f"- Price: ₹{order.item.item_price} x {order.quantity} = ₹{order.item.item_price * order.quantity}\n\n"
            f"Thank you for your purchase!",
            "sohamdas704@gmail.com",
            [user.email],
            fail_silently=False,
        )
        return order
    except Exception as e:
        messages.error(request, f"Error creating order for {cart_item.item.item_name}: {str(e)}")
        return None


def create_orders_from_cart(request, cart_items):
    user = request.user
    orders_created = []

    for cart_item in cart_items:
        order = create_order(cart_item, user, request)
        if order:
            orders_created.append(order)

    return orders_created


def cancel_order(request, order_id):
    order = get_object_or_404(CusOrders, pk=order_id, user=request.user)  # Ensure user owns the order
    user = request.user
    
    if request.method == 'POST':
        order.delete()
        messages.success(request, 'Order cancelled successfully!')
        send_mail(
            "Your Order has been Cancelled",
            f"Dear {order.user},\n\n"
            f"Your order has been Cancelled!\n"                    
            f"Here are the details:\n"
            f"- Item Name: {order.item.item_name}\n"
            f"- Size: {order.size}\n"                
            f"- Quantity: {order.quantity}\n"
            f"- Price: ₹{order.item.item_price} x {order.quantity} = ₹{order.item.item_price * order.quantity}\n\n"
            f"We're sorry to see you go! If you ever change your mind, we'll be here to welcome you back with open arms. See you again soon!",
            "sohamdas704@gmail.com",
            [user.email],
            fail_silently=False,
        )
    else:
        context = {'order': order}
        return render(request, 'clothing/cancel_order.html', context)

    return redirect('clothing:myorders')

genx/clothing/templates/clothing/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>Genx</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
		crossorigin="anonymous"></script>
	<script
		src="https://www.paypal.com/sdk/js?client-id=AWpVGwtslJ_FF4cqTORdFmuqR6QU7pqbiTSmKQC7ON-TyVdJFrlPKojLDkedTtt-IlZE8ZrNh0V1imRL&currency=USD"></script>
</head>

<body>
	<header id="header" class="site-header header-scrolled text-black bg-light">
		<nav id="header-nav" class="navbar navbar-expand-lg px-3">
			<div class="container-fluid">
				<a class="navbar-brand" href="{% url 'clothing:index' %}">
					<img src="/pic/logo.png" class="logo" width="50" height="35" alt="Genx Logo">
				</a>
				<div class="offcanvas-body">
					<ul id="navbar" class="navbar-nav text-uppercase flex-grow-1 pe-3">
						<li class="nav-item">
							<a class="nav-link me-4 active" href="{% url 'clothing:index' %}">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link me-4" href="{% url 'clothing:mens' %}">Mens</a>
						</li>
						<li class="nav-item">
							<a class="nav-link me-4" href="{% url 'clothing:womens' %}">Womens</a>
						</li>
						<li class="nav-item">
							<a class="nav-link me-4" href="{% url 'clothing:kids' %}">Kids</a>
						</li>
						<form action="{% url 'clothing:index' %}" method="POST" class="d-flex ms-auto" role="search">
							{% csrf_token %}
							<input class="form-control me-2" type="search" name="item_name"
								placeholder="Search for products" aria-label="Search" />
							<button class="btn btn-light me-4" type="submit">
								<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
									class="bi bi-search" viewBox="0 0 16 16">
									<path
										d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
								</svg>
							</button>
						</form>
						{% if user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link d-flex position-relative" href="{% url 'clothing:cart_view' %}"
								title="Cart">
								<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor"
									class="bi bi-cart3" viewBox="0 0 16 16">
									<path
										d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2" />
								</svg>
								<span class="badge badge-pill badge-danger notify position-absolute rounded-circle"
									style="top: 0px; right: -4px; z-index: 1; min-width: 16px; height: 18px; line-height: 8px; background-color: #dc3545; color: #fff;">{{
									cart_items_count }}</span>
							</a>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'clothing:myorders' %}" title="My Orders">
								<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor"
									class="bi bi-card-checklist" viewBox="0 0 16 16">
									<path
										d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2z" />
									<path
										d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0M7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0" />
								</svg>
							</a>
						</li>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'profile' %}" title="Profile">
								<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor"
									class="bi bi-person-circle" viewBox="0 0 16 16">
									<path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0" />
									<path fill-rule="evenodd"
										d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1" />
								</svg>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'logout' %}" title="Logout">
								<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor"
									class="bi bi-power" viewBox="0 0 16 16">
									<path d="M7.5 1v7h1V1z" />
									<path
										d="M3 8.812a4.999 4.999 0 0 1 2.578-4.375l-.485-.874A6 6 0 1 0 11 3.616l-.501.865A5 5 0 1 1 3 8.812" />
								</svg></a>
						</li>
						{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'register' %}">Sign Up</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'login' %}">Login</a>
						</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>
	</header>

	{% if messages %}

	{% for message in messages %}
	<div class="alert alert-{{ message.tags }}">
		{{ message }}
	</div>
	{% endfor %}

	{% endif %}

	{% block body %} {% endblock %}
</body>

</html>

genx/clothing/templates/clothing/cart.html
{% extends 'clothing/base.html' %}

{% block body %}

<section class="h-100">
  <div class="container h-100 py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-10">
        <div class="d-flex justify-content-between align-items-center mb-4">
          <h2 class="fw-normal mb-0 text-black">Shopping Cart :</h2>
          <a class="btn btn-primary btn-lg" href="{% url 'clothing:index' %}">Continue Shopping</a>
        </div>
        {% if cart_items %}
        {% for cart_item in cart_items %}
        <div class="card rounded-3 mb-4">
          <div class="card-body p-4">
            <div class="row d-flex justify-content-between align-items-center">
              <div class="col-md-2 col-lg-2 col-xl-2">
                <img src="{{ cart_item.item.item_image }}" class="img-fluid rounded-3"
                  alt="{{ cart_item.item.item_name }}">
              </div>
              <div class="col-md-3 col-lg-3 col-xl-3">
                <p class="lead fw-normal mb-2">{{ cart_item.item.item_name }}</p>
                <p><span class="text-muted">Size: {{ cart_item.size }}</span></p>
              </div>
              <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                <h5>Quantity: {{ cart_item.quantity }}</h5>
              </div>
              <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                <h5>₹{{ cart_item.item.item_price }}</h5>
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2 ">
                <h5 class="mb-0">Total : ₹{{ cart_item.total_price }}</h5>
              </div>
              <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                <a href="{% url 'clothing:remove_from_cart' cart_item.id %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor"
                    class="bi bi-trash3" viewBox="0 0 16 16">
                    <path
                      d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5" />
                  </svg>
                </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        <div class="card mt-4">
          <div class="card-body d-flex justify-content-between align-items-center">
            <h3 class="card-title mb-0">Grand Total:</h3>
            <h2 class="text-end fs-4">₹{{ grand_total }}</h2>
          </div>
          <div class="card-footer d-grid gap-2">
            <a class="btn btn-success btn-lg" href="{% url 'users:payment' grand_total=grand_total %}">Proceed to
              Pay</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% else %}
<h3>Your cart is empty.</h3>
{% endif %}
{% endblock %}

genx/clothing/templates/clothing/detail.html
{% extends 'clothing/base.html' %}
{% block body %}

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-6">
            <img src="{{ item.item_image }}" alt="Clothing Item" class="img-fluid">
        </div>
        <div class="col-lg-6">
            <form method="POST" action="{% url 'clothing:add_to_cart' item.id %}">
                {% csrf_token %}
                <h2>{{ item.item_name }}</h2>
                <p>{{ item.item_desc }}</p>
                <p>Price: ₹{{ item.item_price }}</p>
                <p>Size:
                    <select class="form-control" name="size">
                        <option>XS</option>
                        <option>S</option>
                        <option>M</option>
                        <option>L</option>
                        <option>XL</option>
                    </select>
                </p>
                <p for="qty">Enter Quantity:<input type="number" class="form-control" id="qty" name="qty" value="1"
                        min="1" max="10"></p>
                <button class="btn btn-primary btn-lg btn-block" type="submit">Add to Cart</button>
                <a class="btn btn-secondary btn-lg btn-block" href="{% url 'clothing:index' %}">Back</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

genx/clothing/templates/clothing/kids.html
{% extends 'clothing/base.html' %} {% block body %}
<style>
	.card {
		transition: transform 0.2s;
	}

	.card:hover {
		transform: scale(1.05);
		box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
	}
</style>
<header class="bg-dark py-5">
	<div class="container px-4 px-lg-5 my-5">
		<div class="text-center text-white">
			<h1 class="display-4 fw-bolder">Shop in style</h1>
			<p class="lead fw-normal text-white-50 mb-0">Playful Styles for Happy Childhoods.</p>
		</div>
	</div>
</header>
<section class="py-5">
	<div class="container px-4 px-lg-5 mt-5">
		<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
			{% for item in itemlist %}
			{% url 'clothing:detail' item.id as detail_url %}
			<div class="col mb-5" onclick="window.location.href='{{ detail_url }}'" style="cursor: pointer;">
				<div class="card h-100">
					<img class="card-img-top" src="{{ item.item_image }}" alt="..." />
					<div class="card-body p-4">
						<div class="text-center">
							<h4 class="fw-bolder">{{ item.item_name }}</h4>
							<p class="fw-bolder">{{ item.item_desc }}</p>
							₹{{ item.item_price }}
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</section>
<footer id="footer" class="overflow-hidden">
	<div class="container">
		<div class="row">
			<div class="footer-top-area">
				<div class="row d-flex flex-wrap justify-content-between">
					<div class="col-lg-3 col-sm-6 pb-3">
						<div class="footer-menu">
							<img src="https://mir-s3-cdn-cf.behance.net/projects/404/48ad70142099899.Y3JvcCwzMzk5LDI2NTksMzAyLDA.jpg"
								class="logo" width="150" height="70">
							<p>
							<h6>If you would like to experience the best of online shopping for men, women and kids in
								India, you are at the right place. Genx is the ultimate destination for fashion and
								lifestyle.</h6>
							</p>

						</div>
					</div>
					<div class="col-lg-2 col-sm-6 pb-3">
						<div class="footer-menu text-uppercase">
							<h5 class="widget-title pb-2">Quick Links</h5>
							<ul class="menu-list list-unstyled text-uppercase">
								<li class="menu-item pb-2">
									<a href="#" class="text-dark text-decoration-none">Home</a>
								</li>
								<li class="menu-item pb-2">
									<a href="#" class="text-dark text-decoration-none">About</a>
								</li>
								<li class="menu-item pb-2">
									<a href="#" class="text-dark text-decoration-none">Shop</a>
								</li>
								<li class="menu-item pb-2">
									<a href="#" class="text-dark text-decoration-none">Blogs</a>
								</li>
								<li class="menu-item pb-2">
									<a href="#" class="text-dark text-decoration-none">Contact</a>
								</li>
							</ul>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6 pb-3">
						<div class="footer-menu text-uppercase">
							<h5 class="widget-title pb-2">Help & Info Help</h5>
							<ul class="menu-list list-unstyled">
								<li class="menu-item pb-2">
									<a href="#" class="text-dark text-decoration-none">Track Your Order</a>
								</li>
								<li class="menu-item pb-2">
									<a href="#" class="text-dark text-decoration-none">Returns Policies</a>
								</li>
								<li class="menu-item pb-2">
									<a href="#" class="text-dark text-decoration-none">Shipping + Delivery</a>
								</li>
								<li class="menu-item pb-2">
									<a href="#" class="text-dark text-decoration-none">Contact Us</a>
								</li>
								<li class="menu-item pb-2">
									<a href="#" class="text-dark text-decoration-none">Faqs</a>
								</li>
							</ul>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6 pb-3">
						<div class="footer-menu contact-item">
							<h5 class="widget-title text-uppercase pb-2">Contact Us</h5>
							<p>Do you have any queries or suggestions? <a href="mailto:"
									class="text-decoration-none">genx@gmail.com</a>
							</p>
							<p>If you need support? Just give us a call. <a href="#" class="text-decoration-none">+91
									7002042003</a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<hr>
</footer>
{% endblock %}